project:
  type: website
  output-dir: docs

website:
  navbar:
    title: "Cooper Honeywell"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - adventures.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: visual





